name: Validate & Deploy Content
on:
  push:
    paths:
      - 'app-content.json'
      - 'schema.json'
  pull_request:
    paths:
      - 'app-content.json'
      - 'schema.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: schema.json
          INPUT_JSONS: app-content.json
